// Test: Aggregation on empty relation

.kg create test_empty_agg_n10t103
.kg use test_empty_agg_n10t103

+empty_rel[]

// Aggregations on empty relation
sum_empty(sum<X>) <- empty_rel(X)
count_empty(count<X>) <- empty_rel(X)

?sum_empty(S)
?count_empty(C)

.kg use default
.kg drop test_empty_agg_n10t103
