// Test: Tuple with many columns

.kg create test_large_tuple_n10t77
.kg use test_large_tuple_n10t77

+wide[(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)]

// Query all columns
?wide(A, B, C, D, E, F, G, H, I, J)

// Project subset
subset(A, E, J) <- wide(A, _, _, _, E, _, _, _, _, J)

?subset(A, E, J)

.kg use default
.kg drop test_large_tuple_n10t77
