// Test: Rule Remove Nonexistent Rule
// Description: Tests error when removing from a rule that doesn't exist
.kg create test_rule_remove_nex_n17t15
.kg use test_rule_remove_nex_n17t15
// No rules defined
.rule list
// Error: rule doesn't exist
.rule remove nonexistent 1

.kg use default
.kg drop test_rule_remove_nex_n17t15
