// Test: Rule drop with max aggregation
// Description: Tests dropping a max rule and redefining it

.kg create test_drop_max_n14t126
.kg use test_drop_max_n14t126

+reading[(1, 25), (1, 22), (1, 28), (2, 30), (2, 35)]

+max_temp(Sensor, max<Temp>) <- reading(Sensor, Temp)

?max_temp(X, Y)

.rule drop max_temp

?max_temp(X, Y)

+max_temp(Sensor, max<Temp>) <- reading(Sensor, Temp)

?max_temp(X, Y)

.kg use default
.kg drop test_drop_max_n14t126
