// Test: Sum with negative values

.kg create test_sum_neg_n14t95
.kg use test_sum_neg_n14t95

+amounts[(100,), (-50,), (200,), (-75,), (25,)]

total(sum<X>) <- amounts(X)

?total(T)

.kg use default
.kg drop test_sum_neg_n14t95
