// Test: Set minus self

.kg create test_minus_self_n22t10
.kg use test_minus_self_n22t10

+data[(1,), (2,), (3,)]

// A - A should be empty
minus_self(X) <- data(X), !data(X)

?minus_self(X)

.kg use default
.kg drop test_minus_self_n22t10
