// Test: Unbalanced parentheses error

.kg create test_unbal_parens_n12t23
.kg use test_unbal_parens_n12t23

// This has unbalanced parentheses - should error immediately
+facts[(1, 2, 3]

.kg use default
.kg drop test_unbal_parens_n12t23
