// Test: Unknown function name error

.kg create test_unknown_func_n12t25
.kg use test_unknown_func_n12t25

+values[(1, 2), (3, 4)]

// Call a function that doesn't exist - should error
?values(X, Y), Z = nonexistent_func(X, Y)

.kg use default
.kg drop test_unknown_func_n12t25
