// Test: Division by zero error

.kg create test_div_zero_n12t35
.kg use test_div_zero_n12t35

+nums[(10,), (0,)]

// This should error when X=0
result(X, Y) <- nums(X), Y = 100 / X

?result(X, Y)

.kg use default
.kg drop test_div_zero_n12t35
