// Test: Very long relation name

.kg create test_long_name_n12t56
.kg use test_long_name_n12t56

+this_is_a_very_long_relation_name_that_goes_on_for_quite_some_time[(1,), (2,)]

?this_is_a_very_long_relation_name_that_goes_on_for_quite_some_time(X)

.kg use default
.kg drop test_long_name_n12t56
