#!/usr/bin/env python3
"""Generate scripts/affected-map.toml: which spec categories exercise which
leaf src/ modules.

The map is derived from the statement types found in spec text, with a fixed
statement-type -> module table (STATEMENT_TYPES below). A category's statement
types are matched in its specs, the files they .load and their recorded
transcripts (.iql.out). A module is listed only when a statement type reaches
it and nothing else does; run_snapshot_tests.sh --affected runs the whole
corpus for any other change under src/, so a module missing here costs time
rather than coverage.

The map is not derived from `.debug` plan output, because:
  - recorded plan output exists for only 7 specs, all in 33_meta;
  - a plan is a trace of parsed rules and IR operators (Scan, Join, Map, ...)
    and names no src/ module;
  - .why and .why_not are meta commands that never produce a plan, so
    src/provenance cannot be seen in one at all.
A plan-derived map is a possible follow-up.

Usage:
  ./scripts/gen-affected-map.py   # Rewrite scripts/affected-map.toml
"""

import re
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = PROJECT_DIR / "examples" / "iql"
MAP_FILE = PROJECT_DIR / "scripts" / "affected-map.toml"

VECTOR_FUNCTIONS = (
    r"euclidean|cosine|dot|manhattan|hamming|normalize|vec_\w+|lsh_\w+"
    r"|quantize_\w+|dequantize\w*|\w+_int8|\w+_dequantized|top_k\w*|within_radius"
)
TEMPORAL_FUNCTIONS = (
    r"time_\w+|within_last|intervals_overlap|interval_\w+|point_in_interval"
)

# Statement type -> (pattern over spec and transcript text, modules it reaches)
STATEMENT_TYPES = {
    "why": (r"^(?:> )?\.why(?:_not)?\b", ["src/provenance"]),
    "vector": (
        rf"\b(?:{VECTOR_FUNCTIONS})\s*\(|^(?:> )?\.(?:index|idx)\b",
        ["src/vector_ops.rs", "src/hnsw_index.rs", "src/hnsw_index_tests.rs"],
    ),
    "temporal": (rf"\b(?:{TEMPORAL_FUNCTIONS})\s*\(", ["src/temporal_ops.rs"]),
}

LOAD = re.compile(r"^\.load\s+(\S+)", re.M)
COMMENT = re.compile(r"^\s*//.*$", re.M)


def category_text(category):
    """Specs (helpers included), the files they .load and their transcripts."""
    parts = []
    for spec in sorted(category.rglob("*.iql")):
        if "_pending_" in spec.name:
            continue
        text = spec.read_text()
        parts.append(text)
        for loaded in LOAD.findall(text):
            if (PROJECT_DIR / loaded).is_file():
                parts.append((PROJECT_DIR / loaded).read_text())
        transcript = Path(f"{spec}.out")
        if transcript.is_file():
            parts.append(transcript.read_text())
    return COMMENT.sub("", "\n".join(parts))


def statement_types(text):
    return [
        name
        for name, (pattern, _) in STATEMENT_TYPES.items()
        if re.search(pattern, text, re.M)
    ]


def generate():
    modules = {}
    for category in sorted(p for p in EXAMPLES_DIR.iterdir() if p.is_dir()):
        for name in statement_types(category_text(category)):
            for module in STATEMENT_TYPES[name][1]:
                modules.setdefault(module, []).append(category.name)
    lines = [
        "# Generated by scripts/gen-affected-map.py - do not edit.",
        "# Leaf src/ modules and the spec categories whose statements reach them;",
        "# read by run_snapshot_tests.sh --affected.",
        "",
        "[modules]",
    ]
    for module in sorted(modules):
        categories = ", ".join(f'"{c}"' for c in modules[module])
        lines.append(f'"{module}" = [{categories}]')
    return "\n".join(lines) + "\n"


def main():
    if sys.argv[1:]:
        sys.exit(f"Unknown option: {' '.join(sys.argv[1:])}")
    MAP_FILE.write_text(generate())


if __name__ == "__main__":
    main()
