#!/usr/bin/env python3
"""Generate scripts/affected-map.toml: which spec categories exercise which
leaf src/ modules.

A category's statement types are read from its specs, the files they .load
and their recorded transcripts (.iql.out), which include the plan output of
every `.debug` statement. A module is listed only when a statement type
reaches it and nothing else does; run_snapshot_tests.sh --affected runs the
whole corpus for any other change under src/, so a module missing here costs
time rather than coverage.

Usage:
  ./scripts/gen-affected-map.py           # Rewrite scripts/affected-map.toml
  ./scripts/gen-affected-map.py --check   # Fail if the file is out of date
  ./scripts/gen-affected-map.py --debug   # Also print each category's statement types
"""

import re
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = PROJECT_DIR / "examples" / "iql"
MAP_FILE = PROJECT_DIR / "scripts" / "affected-map.toml"

VECTOR_FUNCTIONS = (
    r"euclidean|cosine|dot|manhattan|hamming|normalize|vec_\w+|lsh_\w+"
    r"|quantize_\w+|dequantize\w*|\w+_int8|\w+_dequantized|top_k\w*|within_radius"
)
TEMPORAL_FUNCTIONS = (
    r"time_\w+|within_last|intervals_overlap|interval_\w+|point_in_interval"
)

# Statement type -> (pattern over spec and transcript text, modules it reaches)
STATEMENT_TYPES = {
    "why": (r"^(?:> )?\.why(?:_not)?\b", ["src/provenance"]),
    "vector": (
        rf"\b(?:{VECTOR_FUNCTIONS})\s*\(|^(?:> )?\.(?:index|idx)\b",
        ["src/vector_ops.rs", "src/hnsw_index.rs", "src/hnsw_index_tests.rs"],
    ),
    "temporal": (rf"\b(?:{TEMPORAL_FUNCTIONS})\s*\(", ["src/temporal_ops.rs"]),
}

LOAD = re.compile(r"^\.load\s+(\S+)", re.M)
COMMENT = re.compile(r"^\s*//.*$", re.M)


def category_text(category):
    """Specs (helpers included), the files they .load and their transcripts."""
    parts = []
    for spec in sorted(category.rglob("*.iql")):
        if "_pending_" in spec.name:
            continue
        text = spec.read_text()
        parts.append(text)
        for loaded in LOAD.findall(text):
            if (PROJECT_DIR / loaded).is_file():
                parts.append((PROJECT_DIR / loaded).read_text())
        transcript = Path(f"{spec}.out")
        if transcript.is_file():
            parts.append(transcript.read_text())
    return COMMENT.sub("", "\n".join(parts))


def statement_types(text):
    return [
        name
        for name, (pattern, _) in STATEMENT_TYPES.items()
        if re.search(pattern, text, re.M)
    ]


def generate(debug):
    modules = {}
    for category in sorted(p for p in EXAMPLES_DIR.iterdir() if p.is_dir()):
        types = statement_types(category_text(category))
        if debug:
            print(f"{category.name}: {' '.join(types) or '-'}", file=sys.stderr)
        for name in types:
            for module in STATEMENT_TYPES[name][1]:
                modules.setdefault(module, []).append(category.name)
    lines = [
        "# Generated by scripts/gen-affected-map.py - do not edit.",
        "# Leaf src/ modules and the spec categories whose statements reach them;",
        "# read by run_snapshot_tests.sh --affected.",
        "",
        "[modules]",
    ]
    for module in sorted(modules):
        categories = ", ".join(f'"{c}"' for c in modules[module])
        lines.append(f'"{module}" = [{categories}]')
    return "\n".join(lines) + "\n"


def main():
    args = set(sys.argv[1:])
    unknown = args - {"--check", "--debug"}
    if unknown:
        sys.exit(f"Unknown option: {' '.join(sorted(unknown))}")
    content = generate("--debug" in args)
    if "--check" in args:
        if not MAP_FILE.is_file() or MAP_FILE.read_text() != content:
            sys.exit(
                f"{MAP_FILE.relative_to(PROJECT_DIR)} is out of date: "
                "run ./scripts/gen-affected-map.py"
            )
        return
    MAP_FILE.write_text(content)


if __name__ == "__main__":
    main()
