// Test: Integer division truncation

.kg create test_div_trunc_n15t48
.kg use test_div_trunc_n15t48

+vals[(7,), (10,), (15,), (-7,), (-10,)]

// Integer division
int_div(X, Y) <- vals(X), Y = X / 3

?int_div(X, Y)

.kg use default
.kg drop test_div_trunc_n15t48
