// Test: Relative complement

.kg create test_rel_comp_n08t80
.kg use test_rel_comp_n08t80

+universe[(1,), (2,), (3,), (4,), (5,)]
+subset[(2,), (4,)]

// Relative complement of subset in universe
+complement(X) <- universe(X), !subset(X)

?complement(X)

.kg use default
.kg drop test_rel_comp_n08t80
