// Test: Outlier detection pattern

.kg create test_outlier_n18t73
.kg use test_outlier_n18t73

+measurements[(10,), (12,), (11,), (100,), (9,), (13,)]

// Find min and max
min_val(min<V>) <- measurements(V)
max_val(max<V>) <- measurements(V)

?min_val(M)
?max_val(M)

.kg use default
.kg drop test_outlier_n18t73
