// Test: Power function

.kg create test_pow_n32t08
.kg use test_pow_n32t08

+base_exp[(2, 0), (2, 1), (2, 3), (3, 2), (10, 2)]

power_val(B, E, R) <- base_exp(B, E), R = POW(B, E)

?power_val(B, E, R)

.kg use default
.kg drop test_pow_n32t08
