// Test: Logarithm function

.kg create test_log_n32t09
.kg use test_log_n32t09

+nums[(1,), (10,), (100,)]

log_val(X, Y) <- nums(X), Y = LOG(X)

?log_val(X, Y)

.kg use default
.kg drop test_log_n32t09
