// Test: Square root function

.kg create test_sqrt_n32t24
.kg use test_sqrt_n32t24

+nums[(0,), (1,), (4,), (9,), (16,)]

sqrt_val(X, Y) <- nums(X), Y = SQRT(X)

?sqrt_val(X, Y)

.kg use default
.kg drop test_sqrt_n32t24
